### PR TITLE
search closes on outside click

### PR DESCRIPTION
**Pull request by jackbilestech**
## Description

Expected Behavior:
- Close search when clicking out of the box (firefox).
- Have close btn or click in window does not close search window (chrome).
- Working buttons (different browsers).

Actual Behavior
- Impossible to close search window (firefox).
- Search window strangely closes when clicking in window or scrolling (chrome).
- Close search buttons not working on mobile (different browsers).

## Related Issue

[Issue](https://github.com/vuestorefront-community/prestashop/issues/75)

## Motivation and Context

Clicking otuside the search bar was not working as intended on Firefox.

## Screenshots (if appropriate):
Peek 2023-01-06 22-42

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by samberrry** [comment]
@jackbilestech thank you for your contribution. I changed the base branch from `master` to `develop`, I think it needs a re-base, would you please check it, I will merge it with `develop` branch. Thank you

**Comment by jackbilestech** [comment]
> @jackbilestech thank you for your contribution. I changed the base branch from `master` to `develop`, I think it needs a re-base, would you please check it, I will merge it with `develop` branch. Thank you

Rebased [here](https://github.com/vuestorefront-community/prestashop/compare/cbab157b6011c0ad82e8faa3c3334a2c4e51241e..7a3c01832e62fd95e412aed15c1b30fcf6979b38)

**Comment by samberrry** [comment]
Screen Shot 2023-01-10 at 5 54 37 AM

@jackbilestech would you please check it. Other old changes are coming within your PR, please create another branch and push ir, or hard-reset the current branch. 
thank you

**Comment by jackbilestech** [comment]
Ahhh I see, no problem. I'll update this now

**Comment by samberrry** [comment]
@jackbilestech Hey,
did you have a chance to check it? 
as I should test and review it. 
if you need any help I'm here to help you, do not hesitate.

many thanks

**Comment by samberrry** [comment]
Hey @jackbilestech,
as I've checked your PR it works very well. I want to add this fix to the next release v.1.3.0, however the current PR needs some branch refinements. 
If possible, please do them, we would be really happy to see you as contributors, if you do not make it ready I will add it in a separate PR.

thank you

**Pull request closed without merging**
